init:
  - git config --global core.autocrlf true

version: '{branch}-{build}'

skip_tags: true

configuration: Release
platform: Any CPU

shallow_clone: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: v8jdw6X6BYov6AvUJRBsPDoJ+iqCjO/RL1hYWnohBcg1jM3Yb2dcMQt7kf4cqjR

before_build:
- cmd: nuget restore Configgy.Encrypter.sln

build:
  project: Configgy.Encrypter.sln
  verbosity: minimal

after_test:
- cmd: >-
    packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[Configgy]* -[Configgy]System.*" -target:"vstest.console.exe" -targetargs:"Configgy.Encrypter.Tests.Unit\bin\%configuration%\Configgy.Encrypter.Tests.Unit.dll" -output:coverage.xml
    
    packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
